### ISSUE TITLE
"import sounddevice as sd" halts python

### ISSUE THREAD

**Issue by starman2k01** [LAION-AI/natural_voice_assistant#11]
main.py gets stuck on Windows 11 "import sounddevice as sd" and simply halts. Win 11 Pro 22635.3140

**Comment by braunale** [comment]
Hey @starman2k01, is there any error message or something that could help to reproduce the error? How do you know that the main.py halts at exactly this import command?

**Comment by starman2k01** [comment]
I executed each line in main.py within python. That line halts with no response.

**Comment by braunale** [comment]
Could you try import sounddevice just in the console or in a different python file, so we could check if its a problem with the sounddevice package itself or with the code in main.py? 
In main.py import sounddevice is executed is the play_audio function which runs in a separated sub process. Maybe it have something todo with this. So lets check first, if you can import sounddevice in a simple python script.

**Comment by starman2k01** [comment]
So I execute these lines one at a time in a python environment. Each executes fine until import sounddevice:
import gc
import time
import torch
import pyaudio
import multiprocessing
import sounddevice as sd
There is no response and python is locked up. I have to crash out.
Executing "import sounddevice" outside of the bud-e environment in python results in:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sounddevice'

Which at least is a response.

**Comment by braunale** [comment]
Did you follow the steps in the installation guide provided in the readme? Were there any errors when you installed the requirements? If you just retry installing sounddevice with 'pip install sounddevice' what response do you get?

**Comment by braunale** [comment]
@starman2k01 Are you still encounter the problem or did you found a solution in the meantime?

**Comment by braunale** [comment]
I will close this issue due to inactivity. If you still encounter this problem, please reopen the issue and provide additional information to reproduce the error.
