### ISSUE TITLE
Can you make ui for this or can I run this in colab?

### ISSUE THREAD

**Issue by Anandyyyt** [LAION-AI/natural_voice_assistant#20]

**Comment by braunale** [comment]
Hey, there is actually a branch in which a user interface is already implemented. It's not polished and completely tested, therefore it is not merged to the main branch yet. But you can checkout the branch **feature-ui** and start the main.py. There should be a local URL printed to the terminal that you can open in a browser.

**Comment by braunale** [comment]
I will close this issue for now. As I mentioned, the UI is already under development and will be merged to main as soon as it is finished and tested. Please checkout the branch **feature-ui** if you want to test the UI already.
