### ISSUE TITLE
error while installing - Pyaudio

### ISSUE THREAD

**Issue by DrGood01** [LAION-AI/natural_voice_assistant#5]
Hello,

Installing requirements, I get this: "ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects"
Running Ubuntu JellyFish with 32 G RAM and NVIDIA GTX 1650

Thanks!

**Comment by jaretburkett** [comment]
Run
```bash
sudo apt install portaudio19-dev
```
And try again

**Comment by DrGood01** [comment]
jaredburkett thank you very much!

**Comment by braunale** [comment]
Hey @DrGood01 thanks for pointing this out and @jaretburkett thanks for the fix :) I added the command to the installation guide in the readme!
