### ISSUE TITLE
pyaudio device selection improvements... and sounddevice/alsa conflicts

### ISSUE THREAD

**Issue by jaggzh** [LAION-AI/natural_voice_assistant#7]
Okay, before I submit PRs I think I should get some feedback. I included a diff below for your reference.

1. Due to the threading used by pyaudio, alsa can get a conflict with the sound device being accessed multiple times. (Fix is below in the patch).
The primary error one would see is:
`OSError: [Errno -9993] Illegal combination of I/O devices`

A more-full error would be something like:
```
File "/home/j/src/ai/bud-e/./main.py", line 50, in record
streamIn = audio.open(format=pyaudio.paFloat32, channels=1,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/.../python3.11/site-packages/pyaudio/__init__.py", line 639, in open
stream = PyAudio.Stream(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/.../python3.11/site-packages/pyaudio/__init__.py", line 441, in __init__
self._stream = pa.open(**arguments)
^^^^^^^^^^^^^^^^^^^^
OSError: [Errno -9993] Illegal combination of I/O devices
```

Online posts led me to find it was related to the threading, and sounddevice being imported globally (in main.py). Placing it in play_audio() addressed it (it's the only place sd is used in main.py).

...Now, on to the pyaudio issue.

2. We currently just hardcode device index 0. I hacked in a global variable containing desired device name priorities (which is why I am not putting it in a PR), and a function to filter/select devices based on those priorities, falling back on error to index 0 like before  (You'll see the sounddevice import change as well as my device selection additions):

```diff
diff --git a/main.py b/main.py
index 908ba82..c5c42f4 100644
--- a/main.py
+++ b/main.py
@@ -3,11 +3,35 @@ import time
 import torch
 import pyaudio
 import multiprocessing
-import sounddevice as sd
+import sys
 from preprocessor import Preprocessor
 from streaming_buffer import StreamBuffer
 from stt_llm_tts_model import STT_LLM_TTS
 
+# Define your pyaudio device preferences here
+dev_pref_names=[ 'pulse', 'pipewire', 'default', ]
+
+def list_pyaudio_devices(audio):
+    print("  Available pyaudio devices:", file=sys.stderr)
+    for i in range(audio.get_device_count()):
+        dev = audio.get_device_info_by_index(i)
+        print((i,dev['name'],dev['maxInputChannels']),
+              file=sys.stderr)
+
+def get_pyaudio_input_idx(audio):
+    list_pyaudio_devices(audio)
+    for pref_name in dev_pref_names:
+        for i in range(audio.get_device_count()):
+            dev = audio.get_device_info_by_index(i)
+            # print(f"[{i}] pref({pref_name}) == dev({dev['name']})")
+            # print(f" {type(pref_name)}) == {type(dev['name'])}")
+            if pref_name == dev['name'].lower() and dev['maxInputChannels'] > 0:
+                print(f"Selecting pyaudio device {dev['name']}",
+                      file=sys.stderr)
+                return i
+    print("Couldn't find a pyaudio device from our dev_pref_names (f{dev_pref_names}). Picking idx 0", file=sys.stderr)
+    list_pyaudio_devices(audio)
+    return 0
 
 def record(audio_buffer, start_recording):
     """Record an audio stream from the microphone in a separate process  
@@ -20,8 +44,10 @@ def record(audio_buffer, start_recording):
 
     # Open audio input stream
     audio = pyaudio.PyAudio()
+    dev_idx = get_pyaudio_input_idx(audio)
+    print(f"Using pyaudio device index {dev_idx}", file=sys.stderr)
     streamIn = audio.open(format=pyaudio.paFloat32, channels=1,
-                            rate=RATE, input=True, input_device_index=0,
+                            rate=RATE, input=True, input_device_index=dev_idx,
                             frames_per_buffer=CHUNK)
     
     while(True):
@@ -45,6 +71,7 @@ def play_audio(audio_output_buffer):
         Args:
             audio_output_buffer: multiprocessing-queue to receive audio data
     """
+    import sounddevice as sd
     fs = 24000
     while(True):
         # get next audio data 
```

**Comment by braunale** [comment]
Hey @jaggzh, thanks for creating this issue and especially for your code suggestion! I have included parts of it in a bugfix regarding pyaudio I am working on at the moment. Selecting the audio device by name is difficult since this can change depending on the os and other factors. However, I've added your list_pyaudio_devices method to the beginning of the main function and added an argument named "audio-device-idx" (with default 0) to select the audio device from the list of available devices. Further, I've added a method to automatically select a sample rate and the number of channels (mono/stereo) that is supported by the given device. Finally as you suggested I moved the import of sounddevice to the record function to avoid conflicts. 

I only could test is on windows, so it would be great if you could check out the branch **bugfix-invalid-samplerate** and try if it works on your machine. If its working finde, I can merge it to the main branch. Happy to hear your feedback!

**Comment by starman2k01** [comment]
To chime in, main.py gets stuck on Windows 11 "import sounddevice as sd" and simply halts.

**Comment by braunale** [comment]
@starman2k01, does this happen on the main branch or the bugfix branch?

**Comment by braunale** [comment]
Merged branch **bugfix-invalid-samplerate** which solves the issues.

**Comment by starman2k01** [comment]
git pull shows no difference. Was this merged into main? I don't see a bugfix release...

**Comment by starman2k01** [comment]
Forcing a git clone has same error. Not resolved?
